data:
    src: "gloss"  # either "gloss" or "text"   # Source - Either Gloss->Pose or Text->Pose (gloss,text)
    trg: "quat"    # Target - 3D Root coordinates and limbs rotations in Quaternions format (4D * N_bones)
    files: "files"    # Filenames for each sequence

    train: "path/to/your/train/dataset"
    dev: "path/to/your/dev/dataset"
    test: "path/to/your/test/dataset"

    max_sent_length: 300 # Max Sentence Length
    skip_frames: 1   # Skip frames in the data, to reduce the data input size
    src_vocab: "path/to/your/vocab/file.txt"  # e.g. here: "./configs/src_vocab.txt"

    mean_bones_lengths: "path/to/your/mean_bones_lengths.txt"  # e.g. here: "./configs/mean_bones_lengths.txt"

training:
    random_seed: 27   # Random seed for initialisation
    optimizer: "adam"   # Chosen optimiser (adam, ..)
    learning_rate: 0.001   # Initial model learning rate
    learning_rate_min: 0.0002 # Learning rate minimum, when training will stop
    weight_decay: 0.0   # Weight Decay
    clip_grad_norm: 5.0   # Gradient clipping value
    batch_size: 64    # Batch Size for training
    scheduling: "plateau"   # Scheduling at training time (plateau, ...)
    patience: 7  # How many epochs of no improvement causes a LR reduction
    decrease_factor: 0.7  # LR reduction factor, after the # of patience epochs
    early_stopping_metric: "dtw" # Which metric determines scheduling (DTW, loss, BT...)
    epochs: 20000  # How many epochs to run for
    validation_freq: 10000  # After how many steps to run a validation on the model
    logging_freq: 250  # After how many steps to log training progress
    eval_metric: "dtw"  # Evaluation metric during training (dtw','bt')
    model_dir: "./results_quat" # Where the model shall be stored
    overwrite: False # Flag to overwrite a previous saved model in the model_dir
    continue: True  # Flag to continue from a previous saved model in the model_dir
    shuffle: True  # Flag to shuffle the data during training
    use_cuda: True  # Flag to use GPU cuda capabilities
    max_output_length: 300 # Max Output Length
    keep_last_ckpts: 1 # How many previous best/latest checkpoints to keep
    loss: "MSE_MGD"  # Loss function MSE_MGD : MSE for root joints + Mean Geodesic Distance for quaternions (added by GF)
    supervised_contrastive_loss: no  # whether to incorporate L_supCont
    sbert_contrastive_loss: no  # whether to incorporate L_sBERTCont

model:
    initializer: "xavier" # Model initialisation (Xavier, ...)
    bias_initializer: "zeros"  # Bias initialiser (Zeros, ...)
    embed_initializer: "xavier" # Embedding initialiser (Xavier, ...)
    trg_size: 199  # Size of target quaternions representation (3D root + N_bones * 4D quaternions = 3 + 49 * 4)
    just_count_in: False # Flag for Just Counter Data Augmentation
    gaussian_noise: True # Flag for Gaussian Noise Data Augmentation
    noise_rate: 5 # Gaussian Noise rate
    future_prediction: 0 # Future Prediction Data Augmentation if > 0
    encoder:  # Model Encoder
        type: "transformer"
        num_layers: 2 # Number of layers
        num_heads: 4  # Number of Heads
        embeddings:
            embedding_dim: 512  # Embedding Dimension
            dropout: 0.0 # Embedding Dropout
        hidden_size: 512 # Hidden Size Dimension
        ff_size: 2048 # Feed-forward dimension (4 x hidden_size)
        dropout: 0.0 # Encoder Dropout
    decoder: # Model Decoder
        type: "transformer"
        num_layers: 2 # Number of layers
        num_heads: 4 # Number of Heads
        embeddings:
            embedding_dim: 512 # Embedding Dimension
            dropout: 0.0 # Embedding Dropout
        hidden_size: 512 # Hidden Size Dimension
        ff_size: 2048 # Feed-forward dimension (4 x hidden_size)
        dropout: 0.0 # Decoder Dropout

    root_loss_scale: 1.0
    quaternions_loss_scale: 1.0
    counter_loss_scale: 1.0