output_folder: "../data"

steps: [
  "get_examples_ids",
  "make_videos",
  "extract_poses",
  "prepro_save_text_file",
  "prepro_save_gloss_file",
  "prepro_save_files_file",
  "prepro_save_skels_file",
  "prepro_save_quat_file",
  "prepro_save_sbert_file",
  "make_verif_videos",
  "compute_mean_bones_lengths",
]

subsets: ["dev", "test", "train"]

paths:
  examples_ids_folder: "examples_ids"
  videos_folder: "videos"
  poses_folder: "skel_sequences"
  dataset_folder: "dataset"
  verif_videos_folder: "verif_videos"
  src_images_folder: "../../raw_data/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/features/fullFrame-210x260px"
  src_annotations_folder: "../../raw_data/PHOENIX-2014-T-release-v3/PHOENIX-2014-T/annotations/manual"

skel_extraction_cfg:
  method: "zelinka2020"
  show_progress_bar: yes
  export_video: no
  verbose: yes

parallelize_skel_extraction: yes
cpu: 24

n_verif_videos:
  test: 10
  dev: 10
  train: 20

quaternions_verif: yes

sentences_embeddings_pretrained_model: "all-MiniLM-L6-v2"  # cf. https://www.sbert.net/docs/sentence_transformer/pretrained_models.html